#/*
#*********************************************************************************************************
#*                                                    MELIS
#*                                    the Easy Portable/Player Develop Kits
#*                                               makefile Module
#*
#*                                    (c) Copyright 2006-2010, kevin.z China
#*                                             All Rights Reserved
#*
#* File    : makefile
#* By      : hot.lee
#* Version : 
#* Date    : 
#* Descript:
#* Update  : date                auther      ver     notes
#*********************************************************************************************************
#*/



#生成输出目标文件
all:
	make -C drv_display
	make -C drv_fm
	make -C drv_ir	
	make -C drv_keyboard
	make -C drv_matrixkey
	make -C drv_power2
	make -C mod_orange  

		
clean:
	make -C drv_display					clean
	make -C drv_fm					clean
	make -C drv_ir					clean
	make -C drv_keyboard					clean
	make -C drv_matrixkey					clean
	make -C drv_power2					clean
	make -C mod_orange					clean
