#ifndef __SETTING_MAIN_H__
#define __SETTING_MAIN_H__

typedef enum {
	SETTING_MAIN_ITEM_ID_RETURN,
	SETTING_MAIN_ITEM_ID_LOCK,
	SETTING_MAIN_ITEM_ID_RESET_PASSWD,
	SETTING_MAIN_ITEM_ID_TIMER,
	SETTING_MAIN_ITEM_ID_SCREEN_SAVER,
	SETTING_MAIN_ITEM_ID_SEASON,
	SETTING_MAIN_ITEM_ID_BASIC,
	SETTING_MAIN_ITEM_ID_NETWORK,
	SETTING_MAIN_ITEM_ID_UPGRADE,
	SETTING_MAIN_ITEM_ID_ALL,
}setting_main_item_id_t;

#endif		