#/*
#*********************************************************************************************************
#*                                                    MELIS
#*                                    the Easy Portable/Player Develop Kits
#*                                               makefile Module
#*
#*                                    (c) Copyright 2006-2010, kevin.z China
#*                                             All Rights Reserved
#*
#* File    : makefile
#* By      : kevin.z
#* Version : v1.0
#* Date    : 2010-9-7 11:24
#* Descript:
#* Update  : date                auther      ver     notes
#*********************************************************************************************************
#*/

all:
	make -C lib_ex
	make -C ui_common
	make -C gesture
	make -C uiconfig
	make -C media_player
	make -C gadget


# 删除生成的中间文件
clean:
	make -C lib_ex clean
	make -C ui_common clean
	make -C gesture clean
	make -C uiconfig clean
	make -C media_player clean
	make -C gadget clean
